TECH_KEYWORDS = {
    "react",
    "redux",
    "javascript",
    "typescript",
    "node.js",
    "express.js",
    "mongodb",
    "mysql",
    "postgresql",
    "redis",
    "python",
    "flask",
    "django",
    "fastapi",
    "machine learning",
    "deep learning",
    "tensorflow",
    "pytorch",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "git",
    "github",
    "rest api",
    "graphql",
    "next.js",
    "tailwind",
    "bootstrap",
    "java",
    "spring",
    "c++",
    "c",
}